[[project]]
name = "Enviame"
desc = "Enviame is a Rust-based message prioritization app using Axum, Tokio, and SQLx, built to explore scalable backend design through real-world use. It supports email and calendar integration with a minimal SSR frontend."
tags = ["Rust", "Axum", "PostgreSQL", "AJAX", "Bootstrap"]
links = [
    { name = "Writeup", url = "./enviame", newtab = false },
    { name = "Demo", url = "https://msg-beta.brianc.tech" },
    { name = "Source", url = "https://github.com/differental/Enviame/" },
]

[[project]]
name = "(WIP) RustyMoves"
desc = "RustyMoves is a lightweight UDP-first protocol framework for real-time apps. It is implemented with Rust and Tokio, and emphasises minimal encoding overhead and resilience to packet loss. A C++ client port is in development."
tags = ["Rust", "Tokio", "Networking", "C++"]
links = [
    { name = "Source", url = "https://github.com/differental/Rusty_Moves/" },
]

[[project]]
name = "(WIP) Mini-RPC"
desc = "Mini-RPC is a compact C++ serialisation & RPC layer that targets near-zero encoding time by leveraging direct memory layouts and ergonomic getter/setter APIs for user types."
tags = ["C++", "Serialisation", "RPC"]
links = [
    { name = "Source", url = "https://github.com/differental/Mini-RPC/" },
]

[[project]]
name = "IDP"
desc = "The Integrated Design Project (IDP) is a group coursework project involving designing and coding in Python an Automated Guided Vehicle (AGV) to complete tasks around a table. Together with a teammate, I was responsible for the software that powers the Raspberry Pi Pico."
tags = ["Python", "RP Pico", "Microcontroller", "AGV"]
links = [
    { name = "Documentation", url = "./idp", newtab = false },
    { name = "Source", url = "https://github.com/differental/IDP-L208/" },
]

[[project]]
name = "ErgTools"
desc = "ErgTools is a simple collection of useful tools for indoor rowing (\"erging\"). Starting from simple CLI tools, it has expanded into a full-stack web application for workout recording and performance analysis."
tags = ["Rust", "Actix", "AJAX", "Tailwind"]
links = [
    { name = "Demo", url = "https://et.brianc.tech" },
    { name = "Source", url = "https://github.com/differental/ErgTools/" },
]
